language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer -V
  - pear version
  - pear config-set auto_discover 1 && pear install pear.phpqatools.org/phpqatools && phpenv rehash
  - phpcs -v

notifications:
  email: false