language: php

php:
  - 5.4

before_script:
  - chmod +x ./build/before_script.sh
  - sh -c ./build/before_script.sh

script:
  - chmod +x ./build/script.sh
  - sh -c ./build/script.sh

notifications:
  email: false