language: php

php:
  - 5.4

before_script:
  - composer -V
  - phpunit -v
  - pear version
  - pear config-set auto_discover 1
  - pear install pear.phpqatools.org/phpqatools
  - phpcs -v

notifications:
  email: false