language: php

php:
- 5.4

env:
  global:
  - secure: |-
      INDyzYyCRh4D98/+3oXWtsg3ZTvm2monkvX5stocr9pU1EgjvR0jt2Yj3f7x
      rXbgFdkmWe3tkMRTw3NjOax0j1r9ujVRg3yMkJVVWEXk+58zo3qCxbr+FswB
      llUbIbYHgvknclEkgbdDd9B5vlGSid20Uvk61bf4mrEb4/jTJk0=
  - secure: |-
      cbF7os/wYgC5ydkWsEynp53OXN/XkcLda2wa1bOoPwxxOA7szb+AithbobZD
      4TE81f9kyvlmXRmUh+ZOFAqyhAuB8LYy9YjxPrT4WlVbLMpB/gK3geG1i/Ui
      HOEdi9W/5JcekWM4QQVjLGVptY9swXMmGs7hdOcPRavnUSKHaDk=
  - WP_VERSION=3.4.2

install:
  - sudo add-apt-repository ppa:nginx/stable -y
  - sudo apt-get update
  - sudo apt-get install nginx
  - sudo apt-get install php5-mysql php5-curl php5-xmlrpc
  - sudo apt-get install php5-fpm

before_script:
- chmod +x ./build/before_script.sh
- chmod +x ./build/sauce_connect_setup.sh
- sh -c ./build/before_script.sh
- sh -c ./build/sauce_connect_setup.sh

script:
- sh -c ./build/script.sh

notifications:
  email: false
